config/routes.rb
Rails.application.routes.draw do

  devise_for :users do
    delete 'logout' => 'sessions#destroy', :as => :destroy_user_session
  end
  root 'students#index'
  
  get "api", to: 'students#api'
  resources :students do
    resources :comments
  end

  resources :categories do
    member do
      put "like", to: "categories#upvote"
      put "upcount", to: "categories#upcount"
    end
  end

  resources :dresses do
    member do
      put "upcount", to: "categories#upcount2"
    end
  end

  resources :friends do
    member do
      put "upcount", to: "categories#upcount3"
    end
  end

  resources :students do
    member do
      put "like", to: "students#upvote"
    end
  end

  resources :blogs

  resources :projects

  resources :pictures

  resources :updates

  resources :videos

end

app/models/blog.rb
class Blog < ActiveRecord::Base
  has_many :notes
end

app/models/category.rb
class Category < ActiveRecord::Base
  acts_as_votable
  has_attached_file :image, :styles => { :large => "800x500#", :medium => "300x300>", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  has_many :comments

  def upcount
    if self.count == nil
      self.count = 0
    end
    self.count += 1
  end

  def self.search(query)
    # where(:title, query) -> This would return an exact match of the query
    where("name like ?", "%#{query}%")
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :student
  belongs_to :user
  belongs_to :profile
  validates :comment, :presence => true

  def self.search(query)
    # where(:title, query) -> This would return an exact match of the query
    where("comment like ?", "%#{query}%")
  end
end

app/models/dress.rb
class Dress < ActiveRecord::Base
  has_attached_file :image, :styles => { :large => "800x500#", :medium => "300x300>", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  def upcount
    if self.count == nil
      self.count = 0
    end
    self.count += 1
  end
end

app/models/friend.rb
class Friend < ActiveRecord::Base
  has_attached_file :image, :styles => { :large => "800x500#", :medium => "300x300>", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  def upcount
    if self.count == nil
      self.count = 0
    end
    self.count += 1
  end
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  has_attached_file :image, :styles => { :large => "800x500#", :medium => "1920x1080#", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  has_attached_file :image, :styles => { :large => "800x500#", :medium => "300x300>", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  validates :name, :presence => true
  validates :quote, :presence => true
  validates :image, :presence => true
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_attached_file :image, :styles => { :large => "800x500#", :medium => "300x300>", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  
end

app/models/student.rb
class Student < ActiveRecord::Base
  acts_as_votable
  has_many :comments
  has_attached_file :image, :styles => { :large => "800x500#", :medium => "300x300>", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  validates :name, :presence => true
  validates :quote, :presence => true
  validates :image, :presence => true

  def self.search(query)
    # where(:title, query) -> This would return an exact match of the query
    where("lower(name) like ?", "%#{query}%")
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_attached_file :image, :styles => { :large => "800x500#", :medium => "300x300>", :thumb => "34x34#" }, :default_url => "/images/:style/missing.png"
         validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new(blog_params)
    if @blog.save
      redirect_to blogs_path
    else
      render :new
    end
  end

  def update
  end

  def destroy
  end

  def index
    @blogs = Blog.all
  end

  def show
    @blog = Blog.find(params[:id])
    # @notes = @blog.notes
  end

  def edit
  end

  private
  def blog_params
    params.require(:blog).permit(:name, :title, :blog, :image)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    if params.has_key?(:student_id)
      @profile_comment = false
      @student = Student.find(params[:student_id])
      @comment = @student.comments.new

      @from = @student
    else
      @profile_comment = true
      @profile = Profile.find(params[:profile_id])
      @comment = @profile.comments.new

      @from = @profile
    end
      respond_to do |format|
        format.html
        format.js
      end
  end

  def create
    if params.has_key?(:student_id)
      @student = Student.find(params[:student_id])
      @comment = Comment.new(comment_params)
      # @comment.user = current_user
      @comment.student = @student
      @comment.save
      respond_to do |format|
        format.html {redirect_to student_path(@student)}
        format.js
      end
    else
      @profile = Profile.find(params[:profile_id])
      @comment = Comment.new(comment_params)
      # @comment.user = current_user
      @comment.profile = @profile
      @comment.save
      respond_to do |format|
        format.html {redirect_to profile_path(@profile)}
        format.js
      end
    end
  end

private
  def comment_params
    params.require(:comment).permit(:comment, :profile_id)
  end
end

app/controllers/updates_controller.rb
class UpdatesController < ApplicationController
  helper_method :sort_column, :sort_direction
  def index
    @students = Student.all.order(sort_column + " " + sort_direction)
    @students_bar = Student.all
  end


  private

    def sort_column
      Student.column_names.include?(params[:sort]) ? params[:sort] : "lastname"
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, {:sort => column, :direction => direction}, {:class => css_class}
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/controllers_helper.rb
module ControllersHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/helpers/updates_helper.rb
module UpdatesHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/blogs/_form.html.erb
<div class="container text-center">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for @blog do |f| %>
      <%= f.text_field :name, class: 'form-control', placeholder: 'Name' %>
      <br>
      <%= f.text_field :title, class: 'form-control', placeholder: 'Enter Title' %>
      <br>
      <%= f.text_field :blog, class: 'form-control', placeholder: 'Enter Title' %>
      <br>

      <%= f.submit class: 'btn btn-default'%>
      <% end %>
    </div>
  </div>
</div>

app/views/blogs/create.html.erb
<h1>Blog#create</h1>
<p>Find me in app/views/blog/create.html.erb</p>

app/views/blogs/destroy.html.erb
<h1>Blog#destroy</h1>
<p>Find me in app/views/blog/destroy.html.erb</p>

app/views/blogs/edit.html.erb
<h1>Blog#edit</h1>
<p>Find me in app/views/blog/edit.html.erb</p>

app/views/blogs/index.html.erb
<div class="container">
  <div class="row">
    <header class="jumbotron hero-spacer text-center">
      <h1>Blogs</h1>
      <p>A collection of user stories</p>
      <%= link_to "New Blog", new_blog_path, class: "btn btn-primary" %>
    </header>

  </div>
    <h1>Blogs 2015</h1>
    <div class="row text-center">
      <% @blogs.each do |blog| %>
      <div class="col-md-3 col-sm-6 hero-feature">
        <div class="thumbnail">
          <%= image_tag blog.image.url(:large) %>
          <div class="caption">
            <%= link_to (blog.created_at.in_time_zone("Pacific Time (US & Canada)").strftime "%B %d, %Y"), blog_path(blog)  %>
            <p><%= blog.name %></p>
          </div>
        </div>
      </div>
      <% end %>
    </div>

  <hr>
</div>

app/views/blogs/new.html.erb
<h1>Blog#new</h1>

<%= render 'form' %>

app/views/blogs/show.html.erb
<div class="container text-center">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">

      <h1><%= @blog.title%></h1>
      <br>

      <%= image_tag @blog.image.url(:medium) %>
      <br>
      <br>
      by <%= @blog.name%>
      <br>
      <%= @blog.created_at.in_time_zone("Pacific Time (US & Canada)").strftime "%B %d, %Y %l:%M %P"  %>
      <hr>
      <%= @blog.blog%>

      <!-- <% if current_user %>
      <p><%= link_to "Edit", edit_student_path(@blog) %></p>
      <p><%= link_to "Delete", student_path(@blog), :method => 'delete' %></p>
      <% end %> -->
      <br>
      <br>
      <p>
        <%= link_to "Return to students", students_path %>
      </p>



    </div>
  </div>
</div>

app/views/blogs/update.html.erb
<h1>Blog#update</h1>
<p>Find me in app/views/blog/update.html.erb</p>