config/routes.rb
Rails.application.routes.draw do

  devise_for :users do
    delete 'logout' => 'sessions#destroy', :as => :destroy_user_session
  end
  root 'students#index'
  
  get "api", to: 'students#api'
  resources :students do
    resources :comments
  end

  resources :categories do
    member do
      put "like", to: "categories#upvote"
      put "upcount", to: "categories#upcount"
    end
  end

  resources :dresses do
    member do
      put "upcount", to: "categories#upcount2"
    end
  end

  resources :friends do
    member do
      put "upcount", to: "categories#upcount3"
    end
  end

  resources :students do
    member do
      put "like", to: "students#upvote"
    end
  end

  resources :blogs

  resources :projects

  resources :pictures

  resources :updates

  resources :videos

end

app/models/blog.rb
class Blog < ActiveRecord::Base
  has_many :notes
end

app/models/category.rb
class Category < ActiveRecord::Base
  acts_as_votable
  has_attached_file :image, :styles => { :large => "800x500#", :medium => "300x300>", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  has_many :comments

  def upcount
    if self.count == nil
      self.count = 0
    end
    self.count += 1
  end

  def self.search(query)
    # where(:title, query) -> This would return an exact match of the query
    where("name like ?", "%#{query}%")
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :student
  belongs_to :user
  belongs_to :profile
  validates :comment, :presence => true

  def self.search(query)
    # where(:title, query) -> This would return an exact match of the query
    where("comment like ?", "%#{query}%")
  end
end

app/models/dress.rb
class Dress < ActiveRecord::Base
  has_attached_file :image, :styles => { :large => "800x500#", :medium => "300x300>", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  def upcount
    if self.count == nil
      self.count = 0
    end
    self.count += 1
  end
end

app/models/friend.rb
class Friend < ActiveRecord::Base
  has_attached_file :image, :styles => { :large => "800x500#", :medium => "300x300>", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  def upcount
    if self.count == nil
      self.count = 0
    end
    self.count += 1
  end
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  has_attached_file :image, :styles => { :large => "800x500#", :medium => "1920x1080#", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  has_attached_file :image, :styles => { :large => "800x500#", :medium => "300x300>", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  validates :name, :presence => true
  validates :quote, :presence => true
  validates :image, :presence => true
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_attached_file :image, :styles => { :large => "800x500#", :medium => "300x300>", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  
end

app/models/student.rb
class Student < ActiveRecord::Base
  acts_as_votable
  has_many :comments
  has_attached_file :image, :styles => { :large => "800x500#", :medium => "300x300>", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  validates :name, :presence => true
  validates :quote, :presence => true
  validates :image, :presence => true

  def self.search(query)
    # where(:title, query) -> This would return an exact match of the query
    where("lower(name) like ?", "%#{query}%")
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_attached_file :image, :styles => { :large => "800x500#", :medium => "300x300>", :thumb => "34x34#" }, :default_url => "/images/:style/missing.png"
         validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new(blog_params)
    if @blog.save
      redirect_to blogs_path
    else
      render :new
    end
  end

  def update
  end

  def destroy
  end

  def index
    @blogs = Blog.all
  end

  def show
    @blog = Blog.find(params[:id])
    # @notes = @blog.notes
  end

  def edit
  end

  private
  def blog_params
    params.require(:blog).permit(:name, :title, :blog, :image)
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  before_action :authenticate_user!, only: [:new, :create]

  def api
    @students = Student.all
    render json: @students
  end

  def index
    if params[:search]
      @students_search = Student.search(params[:search])
      @categories_search = Category.search(params[:search])
      @comments_search = Comment.search(params[:search])
    end

    @students = Student.all.order(:name)
    @categories = Category.all

    respond_to do |format|
      format.html
      format.js
    end
  end



  def show
    @students = Student.all
    @student = Student.find(params[:id])
    @from = @student
    @comment = Comment.new
    @comments = @student.comments
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      redirect_to students_path
    else
      render :new
    end
  end

  def edit
    @student = Student.find(params[:id])
  end

  def update
    @student = Student.find(params[:id])
    if @student.update(student_params)
      redirect_to students_path
    else
      render :edit
    end
  end

  def destroy
    @student = Student.find(params[:id])
    @student.destroy
    redirect_to students_path
  end

  def upvote
    @student = Student.find(params[:id])
    @student.upvote_by current_user
    redirect_to categories_path
  end

private
  def student_params
    params.require(:student).permit(:name, :quote, :facebook, :linkedin, :github, :other, :image, :lastname, :firstname, :age, :gender, :cohort, :internship, :company)
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, {:sort => column, :direction => direction}, {:class => css_class}
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/controllers_helper.rb
module ControllersHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/helpers/updates_helper.rb
module UpdatesHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/students/_form.html.erb
<%= render "layouts/errors", :object => @student %>

<div class="container text-center">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
    <%= form_for @student do |f| %>
      <%= f.text_field :name, class: 'form-control', placeholder: 'Name' %>
      <br>
      <%= f.text_field :lastname, class: 'form-control', placeholder: 'Last Name' %>
      <br>
      <%= f.text_field :firstname, class: 'form-control', placeholder: 'First Name' %>
      <br>
      <%= f.text_field :quote, class: 'form-control', placeholder: 'Enter Your Quote' %>
      <br>
      <%= f.text_field :facebook, class: 'form-control', placeholder: 'Facebook URL' %>
      <br>
      <%= f.text_field :linkedin, class: 'form-control', placeholder: 'LinkedIn URL' %>
      <br>
      <%= f.text_field :github, class: 'form-control', placeholder: 'Github URL' %>
      <br>
      <%= f.text_field :other, class: 'form-control', placeholder: 'Other URL' %>
      <br>
      <%= f.text_field :age, class: 'form-control', placeholder: 'Age' %>
      <br>
      <%= f.text_field :gender, class: 'form-control', placeholder: 'Gender' %>
      <br>
      <%= f.text_field :cohort, class: 'form-control', placeholder: 'Cohort' %>
      <br>
      <%= f.text_field :internship, class: 'form-control', placeholder: 'Internship' %>
      <br>
      <%= f.text_field :company, class: 'form-control', placeholder: 'Company' %>
      <br>
      <%= f.label :image,'Upload An Image'%>
      <br>
      <div id="filefield">
        <%= f.file_field :image %>
      </div>
      <%= f.submit class: 'btn btn-default'%>
    <% end %>
    </div>
  </div>
</div>

app/views/students/_search.html.erb
<div class="col-md-6">

  <% @students_search.each do |student| %>
    <li><%= link_to student.name, student %> - <%= student.quote %></li>
  <% end %>
  <br>
  <% @categories_search.each do |category| %>
    <li><%= link_to category.name, category %> - <%= category.quote %></li>
  <% end %>
  <br>
  <% @comments_search.each do |comment| %>
    <li><%= comment.comment %> </li>
  <% end %>
</div>

app/views/students/edit.html.erb
<h1>Edit Student</h1>

<%= render 'form' %>

app/views/students/index.html.erb
<div class="container">
  <div class="row">
    <header class="jumbotron hero-spacer text-center">
      <h1>EpicodusBook</h1>
      <p>A look back at our journey together.</p>
      <% if current_user %>
      <%= link_to "New Student", new_student_path, class: "btn btn-primary" %>
      <% end %>
      <!-- <%= link_to "New Category", new_category_path, class: "btn btn-primary" %> -->
    </header>
  </div>
  <div id="search-results">
    <% if @students_search %>
      <%= render 'search' %>
    <% end %>
  </div>
  <h1>Students 2015</h1>
  <div class="row text-center">
    <% @students.each do |student| %>
    <div class="col-md-3 col-sm-6 hero-feature">
      <div class="thumbnail">
        <%= image_tag student.image.url(:large) %>
        <div class="caption">
          <%= link_to student.name, student_path(student) %>
          <p><%= student.quote %></p>
        </div>
      </div>
    </div>
    <% end %>
  </div>

  <hr>

</div>

app/views/students/index.js.erb
$('#search-results').html("<%= j render 'search' %>")

app/views/students/new.html.erb
<h1 class="text-center">New Student</h1>

<%= render 'form' %>

app/views/students/show.html.erb
<% content_for(:title, "EpicodusBook | Student") %>

<div class="container text-center">
  <div class="row">
    <header class="jumbotron hero-spacer text-center">
      <h1><%= @student.name%></h1>
      <p><%= @student.quote%></p>
      <% if current_user %>
      <%= link_to "New Student", new_student_path, class: "btn btn-primary" %>
      <% end %>
      <!-- <%= link_to "New Category", new_category_path, class: "btn btn-primary" %> -->
    </header>
  </div>
  <div class="row">
    <div class="col-md-6">
      <div class="well">
        <%= image_tag @student.image.url(:medium) %>
        <br>
        <br>
        <%= link_to "", @student.facebook, class: "icon-social-facebook" %>
        <%= link_to "", @student.linkedin, class: "icon-social-linkedin" %>
        <%= link_to "", @student.github, class: "icon-social-github" %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="well">
        <div id="show-comments">
          <%= render '/comments/comments' %>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container text-center">
  <div class="row">
    <div class="col-md-6">
      <div class="well">

      <p>
        <%= render '/comments/form' %>
      </p>
      <p><%= link_to "Edit", edit_student_path(@student) %></p>
      <!-- <p><%= link_to "Delete", student_path(@student), :method => 'delete' %></p> -->
      <p><%= link_to "Return to students", students_path %></p>
      </div>
    </div>
  </div>
</div>