config/routes.rb
Rails.application.routes.draw do

  devise_for :users do
    delete 'logout' => 'sessions#destroy', :as => :destroy_user_session
  end
  root 'students#index'
  
  get "api", to: 'students#api'
  resources :students do
    resources :comments
  end

  resources :categories do
    member do
      put "like", to: "categories#upvote"
      put "upcount", to: "categories#upcount"
    end
  end

  resources :dresses do
    member do
      put "upcount", to: "categories#upcount2"
    end
  end

  resources :friends do
    member do
      put "upcount", to: "categories#upcount3"
    end
  end

  resources :students do
    member do
      put "like", to: "students#upvote"
    end
  end

  resources :blogs

  resources :projects

  resources :pictures

  resources :updates

  resources :videos

end

app/models/blog.rb
class Blog < ActiveRecord::Base
  has_many :notes
end

app/models/category.rb
class Category < ActiveRecord::Base
  acts_as_votable
  has_attached_file :image, :styles => { :large => "800x500#", :medium => "300x300>", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  has_many :comments

  def upcount
    if self.count == nil
      self.count = 0
    end
    self.count += 1
  end

  def self.search(query)
    # where(:title, query) -> This would return an exact match of the query
    where("name like ?", "%#{query}%")
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :student
  belongs_to :user
  belongs_to :profile
  validates :comment, :presence => true

  def self.search(query)
    # where(:title, query) -> This would return an exact match of the query
    where("comment like ?", "%#{query}%")
  end
end

app/models/dress.rb
class Dress < ActiveRecord::Base
  has_attached_file :image, :styles => { :large => "800x500#", :medium => "300x300>", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  def upcount
    if self.count == nil
      self.count = 0
    end
    self.count += 1
  end
end

app/models/friend.rb
class Friend < ActiveRecord::Base
  has_attached_file :image, :styles => { :large => "800x500#", :medium => "300x300>", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  def upcount
    if self.count == nil
      self.count = 0
    end
    self.count += 1
  end
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  has_attached_file :image, :styles => { :large => "800x500#", :medium => "1920x1080#", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  has_attached_file :image, :styles => { :large => "800x500#", :medium => "300x300>", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  validates :name, :presence => true
  validates :quote, :presence => true
  validates :image, :presence => true
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_attached_file :image, :styles => { :large => "800x500#", :medium => "300x300>", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  
end

app/models/student.rb
class Student < ActiveRecord::Base
  acts_as_votable
  has_many :comments
  has_attached_file :image, :styles => { :large => "800x500#", :medium => "300x300>", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  validates :name, :presence => true
  validates :quote, :presence => true
  validates :image, :presence => true

  def self.search(query)
    # where(:title, query) -> This would return an exact match of the query
    where("lower(name) like ?", "%#{query}%")
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_attached_file :image, :styles => { :large => "800x500#", :medium => "300x300>", :thumb => "34x34#" }, :default_url => "/images/:style/missing.png"
         validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new(blog_params)
    if @blog.save
      redirect_to blogs_path
    else
      render :new
    end
  end

  def update
  end

  def destroy
  end

  def index
    @blogs = Blog.all
  end

  def show
    @blog = Blog.find(params[:id])
    # @notes = @blog.notes
  end

  def edit
  end

  private
  def blog_params
    params.require(:blog).permit(:name, :title, :blog, :image)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def new
    @category = Category.new
  end

  def index
    @categories = Category.all.order('count desc')
    @dresses = Dress.all.order('count desc')
    @friends = Friend.all.order('count desc')
  end

  def create
    @category = Category.new({:name => params['name'], :quote => params['quote'], :image => params['image']})
    if @category.save
    end
    @dress = Dress.new({:name => params['name2'], :quote => params['quote2'], :image => params['image2']})
    if @dress.save
    end
    @friend = Friend.new({:name => params['name3'], :quote => params['quote3'], :image => params['image3']})
    if @friend.save
    end
      redirect_to categories_path
  end

  def show
    @students = Student.all
  end

  def upvote
    @category = Category.find(params[:id])
    @category.upvote_by current_user
    redirect_to categories_path
  end

  def upcount
    @category = Category.find(params[:id])
    @category.upcount
    @category.save
    respond_to do |format|
      format.html {redirect_to categories_path(@category)}
      format.js
    end
  end

  def upcount2
    @dress = Dress.find(params[:id])
    @dress.upcount
    @dress.save
    respond_to do |format|
      format.html {redirect_to categories_path(@dress)}
      format.js
    end
  end

  def upcount3
    @friend = Friend.find(params[:id])
    @friend.upcount
    @friend.save
    respond_to do |format|
      format.html {redirect_to categories_path(@friend)}
      format.js
    end
  end

  # private
  #   def category_params
  #     params.require(:category).permit(:name, :quote, :image)
  #   end
end

app/controllers/updates_controller.rb
class UpdatesController < ApplicationController
  helper_method :sort_column, :sort_direction
  def index
    @students = Student.all.order(sort_column + " " + sort_direction)
    @students_bar = Student.all
  end


  private

    def sort_column
      Student.column_names.include?(params[:sort]) ? params[:sort] : "lastname"
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, {:sort => column, :direction => direction}, {:class => css_class}
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/controllers_helper.rb
module ControllersHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/helpers/updates_helper.rb
module UpdatesHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/categories/_form.html.erb
<div class="container text-center">

  <div class="row">
    <div class="col-md-6 col-md-offset-3">
    <%= form_tag("/categories", class: 'form-inline', method: "post", multipart: true) do %>
    <h3>Funny</h3>
      <%= text_field_tag :name, "", class: 'form-control', placeholder: "Enter Name" %>
      <br>
      <br>
      <%= text_field_tag :quote, "", class: 'form-control', placeholder: "Enter Name" %>
      <br>
      <br>
      <%= label_tag :image,'Upload An Image'%>
      <br>
      <div id="filefield">
        <%= file_field_tag :image %>
      </div>
      <h3>Dress</h3>
      <%= text_field_tag :name2, "", class: 'form-control', placeholder: "Enter Name"  %>
      <br>
      <br>
      <%= text_field_tag :quote2, "", class: 'form-control', placeholder: "Enter Name"  %>
      <br>
      <%= label_tag :image2,'Upload An Image'%>
      <br>
      <div id="filefield">
        <%= file_field_tag :image2 %>
      </div>
      <h3>Friend</h3>
      <%= text_field_tag :name3, "", class: 'form-control', placeholder: "Enter Name"  %>
      <br>
      <br>
      <%= text_field_tag :quote3, "", class: 'form-control', placeholder: "Enter Name"  %>
      <br>
      <%= label_tag :image3,'Upload An Image'%>
      <br>
      <div id="filefield">
        <%= file_field_tag :image3 %>
      </div>
      <%= submit_tag 'Submit', class: 'btn btn-default'%>
    <% end %>
    </div>
  </div>

</div>

app/views/categories/index.html.erb
<div class="container">
  <div class="row">
    <header class="jumbotron hero-spacer text-center">
      <h1>Categories</h1>
      <p>A fun way to find out what others think about you</p>
      <!-- <%= link_to "New Category", new_category_path, class: "btn btn-primary" %> -->
    </header>
  </div>
    <h1>Most Funny</h1>
    <div class="row text-center">
      <% @categories.each do |category| %>
      <div class="col-md-3 col-sm-6 hero-feature">
        <div class="thumbnail">
          <%= image_tag category.image.url(:large) %>
          <div class="caption">
            <%= category.name %> - <%= category.quote %></p>
            <%= link_to "Upvote", upcount_category_path(category), method: "put", remote: true %>
            <div id="total-votes-<%= category.id %>">
              <%= category.count %>
            </div>
          </div>
        </div>
      </div>
      <% end %>
    </div>
    <hr>

    <h1>Best Dressed</h1>
    <div class="row text-center">
      <% @dresses.each do |dress| %>
      <div class="col-md-3 col-sm-6 hero-feature">
        <div class="thumbnail">
          <%= image_tag dress.image.url(:large) %>
          <div class="caption">
            <%= dress.name %> - <%= dress.quote %>
            <br>
            <%= link_to "Upvote", upcount_dress_path(dress), method: "put", remote: true %>
            <div id="total-dress-<%= dress.id %>">
              <%= dress.count %>
            </div>
          </div>
        </div>
      </div>
      <% end %>
    </div>

    <hr>

    <h1>Friendliest</h1>
    <div class="row text-center">
      <% @friends.each do |friend| %>
      <div class="col-md-3 col-sm-6 hero-feature">
        <div class="thumbnail">
          <%= image_tag friend.image.url(:large) %>
          <div class="caption">
            <%= friend.name %> - <%= friend.quote %>
            <br>
            <%= link_to "Upvote", upcount_friend_path(friend), method: "put", remote: true %>
            <div id="total-friend-<%= friend.id %>">
              <%= friend.count %>
            </div>
          </div>
        </div>
      </div>
      <% end %>
    </div>

    <hr>
</div>

app/views/categories/new.html.erb
<h1 class="text-center">New Category</h1>

<%= render 'form' %>

app/views/categories/show.html.erb
<div class="container">
  <div class="row">
    <div class="row text-center">
      <% @students.each do |student| %>
      <div class="col-md-3 col-sm-6 hero-feature">
        <div class="thumbnail">
          <%= image_tag student.image.url(:large) %>
          <div class="caption">
            <%= link_to student.name, student_path(student) %>
            <p><%= student.quote %></p>
            <p><%= link_to "Upvote", like_student_path(student), method: "put" %></p>
            <p><%= student.get_upvotes.size %></p>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/categories/upcount.js.erb
$("#total-votes-<%= @category.id %>").html("<%= @category.count %>")

app/views/categories/upcount2.js.erb
$("#total-dress-<%= @dress.id %>").html("<%= @dress.count %>")

app/views/categories/upcount3.js.erb
$("#total-friend-<%= @friend.id %>").html("<%= @friend.count %>")